name: quid_flutter
description: QuID Flutter SDK for quantum-resistant authentication
version: 1.0.0
homepage: https://github.com/nym-corp/quid

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Cryptography and security
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  
  # Device and hardware integration
  local_auth: ^2.1.6
  device_info_plus: ^9.1.0
  flutter_secure_storage: ^9.0.0
  
  # QR code functionality
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.2
  
  # State management and utilities
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  
  # Platform integration
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  
  # Notifications
  flutter_local_notifications: ^16.1.0
  firebase_messaging: ^14.7.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.2

flutter:
  plugin:
    platforms:
      android:
        package: com.quid.flutter
        pluginClass: QuIDFlutterPlugin
      ios:
        pluginClass: QuIDFlutterPlugin

  assets:
    - assets/images/